name: Django CD

on:
  workflow_run:
    workflows: ["Django CI"]
    types:
      completed: [success]
  push:
    branches: [ "main" ]

jobs:
  deploy:
    # Solo se ejecuta si el CI ha pasado con éxito o si haces push a main
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Render
        # Este comando "despierta" a Render para que empiece el despliegue
        run: |
          curl -X GET ${{ secrets.RENDER_DEPLOY_HOOK }}
