name: Django CD

on:
  workflow_run:
    workflows: ["Django CI"] # Se activa solo cuando el CI termina
    types:
      completed: [success] # Solo si el CI ha salido bien (checks en verde)
  push:
    branches: [ "main" ] # Opcional: también permite disparo manual al subir a main

jobs:
  deploy:
    # Condición de seguridad: solo ejecuta si el CI fue exitoso
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Render
        # Este comando hace la llamada mágica a Render usando el Secret que has guardado
        run: |
          curl -X GET ${{ secrets.RENDER_DEPLOY_HOOK }}
